apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-monitor
  namespace: demo  
spec:
  selector:
    matchLabels:
      app: api  
  endpoints:
  - interval: 15s
    targetPort: 8080 
    path: /metrics