apiVersion: apps/     # 🔴 Cố tình xóa chữ v1 để xem CI có bắt được lỗi không
kind: Deployment
metadata:
  name: web-config
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "0" # Chạy thứ nhì (sau namespace)
data:
  MESSAGE: "hello from gitops 2026"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Chạy thứ ba (khi đã có ConfigMap)
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx:1.27
        envFrom:
        - configMapRef:
            name: web-config # Pod đọc data từ ConfigMap một cách an toàn
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "2" # Chạy cuối cùng khi Pod đã lên xong
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80